import canonicalLaneMathlib.AdmissibleClass

namespace HautevilleHouse
namespace CriticalPointsFunctionalsContextPdesCanonicalLaneLean

end CriticalPointsFunctionalsContextPdesCanonicalLaneLean
end HautevilleHouse
